package com.example.SmartPark.navigation

const val PROFILE_URL = "profile"
const val SIGNUP_URL = "signup"
const val LOGIN_URL = "login"
const val DASHBOARD_URL = "DASH"
const val ADD_SPACES_URL = "add_spaces"
const val VIEW_SPACES_URL = "view_spaces"
const val ROUT_ABOUT = "ABOUT"
const val ROUT_NOTIFICATION = "NOTIFICATION"

const val SPLASH_URL = "Splash"
const val USER_URL = "USER"
const val UHURU_URL = "uhuru"
const val FURAHA_URL = "FURAHA"
const val STAREHE_URL = "STAREHE"
const val SARIT_URL = "SARIT"
const val SAMARA_URL = "SAMARA"
const val SWARI_URL = "SWARI"
const val SALAMA_URL = "SALAMA"
const val GREEN_URL = "GREEN"
const val GARDEN_URL = "GARDEN"
const val TSAVO_URL = "TSAVO"
const val UPARK_URL = "UPARK"
const val QUIVER_URL = "QIUVER"
const val VALLEY_URL = "VALLEY"
const val ELGON_URL = "ELGON"
const val RALLY_URL = "RALLY"
const val RENTER_URL = "RENTER"
const val RSIGNUP_URL = "RSIGNUP"